config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :bookings
  resources :shows
  resources :time_slots
  resources :movies
  resources :screens
  root 'bookings#index'
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  get 'populate_show', to: 'bookings#populate_show', as: 'populate_show'
  get 'populate_screen', to: 'bookings#populate_screen', as: 'populate_screen'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/screen.rb
class Screen < ApplicationRecord
  has_many :shows
  has_many :movies, through: :shows
  validates :name, presence: true
end

app/controllers/screens_controller.rb
class ScreensController < ApplicationController
  before_action :set_screen, only: [:show, :edit, :update, :destroy]

  # GET /screens
  # GET /screens.json
  def index
    @screens = Screen.all
  end

  # GET /screens/1
  # GET /screens/1.json
  def show
  end

  # GET /screens/new
  def new
    @screen = Screen.new
  end

  # GET /screens/1/edit
  def edit
  end

  # POST /screens
  # POST /screens.json
  def create
    @screen = Screen.new(screen_params)

    respond_to do |format|
      if @screen.save
        format.html { redirect_to @screen, notice: 'Screen was successfully created.' }
        format.json { render :show, status: :created, location: @screen }
      else
        format.html { render :new }
        format.json { render json: @screen.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /screens/1
  # PATCH/PUT /screens/1.json
  def update
    respond_to do |format|
      if @screen.update(screen_params)
        format.html { redirect_to @screen, notice: 'Screen was successfully updated.' }
        format.json { render :show, status: :ok, location: @screen }
      else
        format.html { render :edit }
        format.json { render json: @screen.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /screens/1
  # DELETE /screens/1.json
  def destroy
    @screen.destroy
    respond_to do |format|
      format.html { redirect_to screens_url, notice: 'Screen was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_screen
      @screen = Screen.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def screen_params
      params.require(:screen).permit(:name, :seats)
    end
end

app/helpers/screens_helper.rb
module ScreensHelper
end

app/views/screens/_form.html.erb
<%= form_with(model: screen, local: true) do |form| %>
  <% if screen.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(screen.errors.count, "error") %> prohibited this screen from being saved:</h2>

      <ul>
        <% screen.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :seats %>
    <%= form.number_field :seats %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/screens/edit.html.erb
<h1>Editing Screen</h1>

<%= render 'form', screen: @screen %>

<%= link_to 'Show', @screen %> |
<%= link_to 'Back', screens_path %>

app/views/screens/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Screens</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Seats</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @screens.each do |screen| %>
      <tr>
        <td><%= screen.name %></td>
        <td><%= screen.seats %></td>
        <td><%= link_to 'Show', screen %></td>
        <td><%= link_to 'Edit', edit_screen_path(screen) %></td>
        <td><%= link_to 'Destroy', screen, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Screen', new_screen_path %>

app/views/screens/new.html.erb
<h1>New Screen</h1>

<%= render 'form', screen: @screen %>

<%= link_to 'Back', screens_path %>

app/views/screens/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @screen.name %>
</p>

<p>
  <strong>Seats:</strong>
  <%= @screen.seats %>
</p>

<%= link_to 'Edit', edit_screen_path(@screen) %> |
<%= link_to 'Back', screens_path %>