config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :bookings
  resources :shows
  resources :time_slots
  resources :movies
  resources :screens
  root 'bookings#index'
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  get 'populate_show', to: 'bookings#populate_show', as: 'populate_show'
  get 'populate_screen', to: 'bookings#populate_screen', as: 'populate_screen'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>The Movie Booking System is designed by Vyankatesh Madgundi</small>
  <nav>
    <ul>
      <li><%= link_to "About",   '#' %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MovieBookingSystem</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://code.jquery.com/jquery-3.3.1.js"></script>
  </head>

  <body>
    <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <%= link_to "Movie Booking", '#', id: "logo" %>
        <nav>
          <ul class="nav navbar-nav navbar-right">
	    <li><%= link_to "Home", movies_path %></li>
	    <% if current_user %>
	      <li><%= link_to 'Orders', bookings_path %></li>
	      <li><%= link_to 'Admin', rails_admin_path %></li>
	      <li><%= link_to 'Log Out', logout_path %></li>
            <% else %>
              <li><%= link_to 'Sign Up', signup_path %> or </li>
	      <li><%= link_to 'Log In', login_path %></li>
	    <% end %>
          </ul>
        </nav>
      </div>
    </header>
    <div class="container">
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>